name: Run ESLint on pull request

on:
  pull_request: {}

jobs:
  eslint-plugin-filenames-simple:
    name: eslint-plugin-filenames-simple
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: epaew/eslint-plugin-filenames-simple
          ref: master
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.x
          cache: yarn
      - run: yarn install --frozen-lockfile

      - run: yarn upgrade "@epaew/eslint-config@git://github.com/epaew/eslint-config.git#${{ github.event.pull_request.head.sha }}"
      - run: yarn build && yarn upgrade --latest eslint-plugin-filename-simple

      - run: yarn run eslint

      - name: Reset local changes
        run: git checkout . && yarn

  react-liff:
    name: react-liff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: epaew/react-liff
          ref: master
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.x
          cache: yarn
      - run: yarn install --frozen-lockfile

      - run: yarn upgrade "@epaew/eslint-config@git://github.com/epaew/eslint-config.git#${{ github.event.pull_request.head.sha }}"

      - run: yarn run eslint

      - name: Reset local changes
        run: git checkout . && yarn
